### ISSUE TITLE
Latest Update broken

### ISSUE THREAD

**Issue by raguay** [pomdtr/popcorn#8]
I just updated and tried to use the address bar feature, but it will not load now due to:

Could not load icon 'icons/16.png' specified in 'icons'.
Could not load manifest.

**Comment by raguay** [comment]
No. I just tried to load the one that I used for Chrome.

**Comment by pomdtr** [comment]
Can you send me the content of your version of the repository as a zip ?

**Comment by raguay** [comment]
Actually, I did another git pull and recompiled everything. It is now
working. But, all of my use of Nerd Fonts is now a box. Is there a way to
specify the use of FiraCode Nerd Fonts?

**Comment by pomdtr** [comment]
Not currently, but I'll add support for custom theme / fonts later :)

Closing this then :)
